### ISSUE TITLE
Unable to get results reported in the paper

### ISSUE THREAD

**Issue by ji-xin** [PingChang818/TDSTF#1]
Hello @PingChang818 , thank you so much for providing the source code for the interesting paper. I've been trying to reproduce the results from the paper, but haven't been able to do so.

So I followed the readme file, downloaded the data, ran through preprocessing, and did training and evaluation. There wasn't any problem aside from getting the paths right for the dataset.

I trained the model twice with `python main.py`, and evaluated each checkpoint twice. That gave us 4 results:

model 1 run 1
CRPS: 0.7520603882639032
MSE: 622.348388671875

model 1 run 2
CRPS: 0.5939008311221474
MSE: 1333.6546630859375

model 2 run 1
CRPS: 0.830156125520405
MSE: 232.1817626953125

model 2 run 2
CRPS: 0.7796238849037572
MSE: 774.9886474609375

I understand that there is some inevitable randomness in diffusion models, but these results seem far away from Table 2. Is it correct to use hyperparameters in `config/base.yaml`? Is there something else that I'm missing? Thanks!

**Comment by PingChang818** [comment]
Hello @ji-xin ,
Thank you for pointing out! I made a mistake on the dataset link. It should be without "demo". Please try the correct one:
https://physionet.org/content/mimiciii/1.4/
The model works with the 6.2GB zip file.

**Comment by ji-xin** [comment]
Thanks a lot for the reply. With the correct dataset it yields:

test1: CRPS=0.439 and MSE=0.384
test2: CRPS=0.438 and MSE=0.390
