### ISSUE TITLE
gt=samples_y[:,2] ?【the calculation of MSE】

### ISSUE THREAD

**Issue by FortunateStarstar86** [PingChang818/TDSTF#3]
I'm sorry to bother you due to a question I don't understand, the value of "samples_y" in the "forecast" function has been changed and is no longer equal to the original ground truth【pic 1】, why is gt=samples_y[:,2]【pic 2】. In that case is the MSE calculation no longer correct?

**Comment by FortunateStarstar86** [comment]
![35d14172251a6002eaeea36dc52fe27](https://github.com/PingChang818/TDSTF/assets/69461421/ca423458-0b1c-4931-bac4-b45f2eab2c1b)
【pic 1】
![fde597af85ee72e72e7df88b79f69a2](https://github.com/PingChang818/TDSTF/assets/69461421/56730bf4-2893-4a28-a616-a1f2a91c60f1)
【pic 2】

**Comment by FortunateStarstar86** [comment]
looking forward to your reply!~

**Comment by PingChang818** [comment]
Hi FortunateStarstar86,
samples_y is initialized to pure noise before the diffusion process, through which it turns into the predicted values. Of course it has nothing to do with the ground truth.
